### PR TITLE
App would occasionally stop when trying to update prices

### PR DESCRIPTION
**Pull request by albri**
Added a simple if statement to verify whether prices were returned from the api so that it didn't try and use the prices variable on an empty object.

### CODE REVIEW

**Comment by hunterjm** [comment]
Looks good. It appears the builds are failing, most likely due to a linter error for the missing semi-colon. Add that in and I would be happy to merge.

**Comment by albri** [comment]
That seems to have fixed it. Thanks for app!

**Comment by dham84** [comment]
Can you guys merge this fix?

**Comment by ylms** [comment]
This needs to be pulled...

**Comment by hunterjm** [comment]
App will be updated once #200 is merged in.

**Pull request merged**
